### ISSUE TITLE
Cmake based build?

### ISSUE THREAD

**Issue by psteinb** [StephanPreibisch/FourierConvolutionCUDALib#1]
Hi Stephan,

would it be OK if I fork and add cmake cross platform builds?

best,
P

**Comment by StephanPreibisch** [comment]
Absolutely! Just so you know, we tried this before and it did not really work too well for some reasons I do not remember. If it works it would be great if you could also do it for this one: https://github.com/StephanPreibisch/SeparableConvolutionCUDALib - it is basically the same, just for separable convolution. Thanks so much, Stephan

**Comment by psteinb** [comment]
hi Stephan,
ok, if things go well with porting this library, I may consider the other one as well. Can you please specify how the produced library for this repo is expected to be named? Your code in SPIM_Registration looks for:
`Convolution3D_fftCUDAlib`
( see https://github.com/bigdataviewer/SPIM_Registration/blob/0468724607a15efa3b618e9886e497ff6f508827/src/main/java/fiji/plugin/Multi_View_Deconvolution.java#L827 )

Judging the from the name of this repo, I was expecting 
`libFourierConvolutionCUDALib.*`

Can you please give me a hint?
Thanks,
P

PS. Building on Linux and OSX seems to work. But I'd be grateful if other people would validate this:
https://github.com/psteinb/FourierConvolutionCUDALib/tree/adding_cmake

**Comment by psteinb** [comment]
ok, the adding_cmake branch is getting stable now. I'd be happy if it would be merged.
