### ISSUE TITLE
Use libc++ instead of libstdc++ on Mac    

### ISSUE THREAD

**Issue by maweigert** [StephanPreibisch/FourierConvolutionCUDALib#12]
Hey, 

On my Mac (10.10.5, clang Apple LLVM version 7.0.2 , cmake version 2.8.12.1) the build fails with a 
ld: symbol(s) not found for architecture x86_64
error, which is caused by linking against libstdc++ instead of the Mac native  libc++ .

You should probably just change line 87 in CMakeLists.txt to

IF(APPLE)
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libc++")
ELSE(APPLE)
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libstdc++")
ENDIF(APPLE)

which makes it build again.

**Comment by psteinb** [comment]
I added your suggested fix with adfde1e18b6cfd01bfe8807dafd37a371874525c

I'll close this ticket as soon as the code runs on my osx build bot.

**Comment by psteinb** [comment]
watchout that nvcc 7.0 doesn't play well with boost 1.58 and above on OSX 10.10.5 Yosemite
