### ISSUE TITLE
cannot open include file 'cufft_test.cuh'

### ISSUE THREAD

**Issue by cloudsforest** [StephanPreibisch/FourierConvolutionCUDALib#14]
Hi Stephan,

When I build the package, an error shows and I don't have any clue what is wrong. 

I am using win7, have installed microsoft visualstudio 2013, boost1.58 and CUDA7.5.18.

Thank you very much.

Regards
Chen Qian

![cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/369082/14357021/e73f09a8-fcde-11e5-8e04-90fe7a0f94bc.jpg)

**Comment by psteinb** [comment]
That was my mistake. I am on it!

**Comment by psteinb** [comment]
ok, fixed and tested in Linux with 554a96b64422a1e59ddaef427043103030b4b85c. Please crosscheck under windows and report the result. Sorry again!

**Comment by StephanPreibisch** [comment]
Thanks so much @psteinb!

**Comment by cloudsforest** [comment]
Hi Stephan,

Thank you so much. But seems to have some syntax error. 

Regards
Chen

![cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/369082/14424955/ff7275dc-ffdb-11e5-99f9-12420d5d112c.jpg)

**Comment by psteinb** [comment]
Chen, can you please delete the build directory, then pull from master 
and try again. the error that you pasted confuses me. If I am not 
mistaken, it says that you boost build causes the error. Note that you 
can use this library without boost as well! Then the tests are not 
build, but the .so/.dll will be produced anyhow.

**Comment by cloudsforest** [comment]
Stephan, I ran it without boost, and it passed. The dll was there. 

Thank you.

**Comment by psteinb** [comment]
chen, just a minor thing ... my name is not stephan. :D

**Comment by cloudsforest** [comment]
Sorry Peter  :p
