### ISSUE TITLE
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.

### ISSUE THREAD

**Issue by lacan** [StephanPreibisch/FourierConvolutionCUDALib#16]
Hi I've just finished compiling the .dll under Win10 usint cmake as per your instructions. However running your Multiview Deconvolution from the Multiview Reconstruction Application I get the following notice

```
Trying to load following library: C:\Fiji.app\FourierConvolutionCUDALib.dll
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using device Quadro K5200 (id=0, mem=8192MB (8192MB free), CUDA capability 3.5)
```

What does that mean and what is an up to date version in this case? I am using the 7.5 version of the CUDA toolbox and Visual Studio Community 2013

Best

Oli

**Comment by psteinb** [comment]
checking the source code of this library, I can say for sure, that this 
output is NOT coming from this library. this is coming from the java side.

**Comment by lacan** [comment]
Dear @psteinb thank you very much for the info!

**Comment by psteinb** [comment]
hey @lacan is this problem solved?

**Comment by psteinb** [comment]
I'll close this issue now. Please reopen if need be.

**Comment by StephanPreibisch** [comment]
Hi, I added new functionality to the CUDA-based Gaussian convolution providing basic functionality that at some point was supposed to also go into the FFT-based convolution, which did not happen. So it just complains that some simple functions are missing. This is not really important.
