### ISSUE TITLE
Problems building against CUDA 8.0

### ISSUE THREAD

**Issue by aarpon** [StephanPreibisch/FourierConvolutionCUDALib#17]
When building against CUDA 8.0 I get the following error:

`identifier "CUFFT_COMPATIBILITY_NATIVE" is undefined`

from `convolution3Dfft.cu` on line 256:

``` language=c++
CUFFT_ERROR(cufftSetCompatibilityMode(fftPlanFwd,CUFFT_COMPATIBILITY_NATIVE));
```

Checking in the CUDA documentation, I saw that `cufftSetCompatibilityMode()` is deprecated in CUDA 8.0. It seems however that it is basically already removed...

**Comment by psteinb** [comment]
I'll fix that tomorrow. Haven't installed CUDA 8 yet. Thanks for reporting.

**Comment by psteinb** [comment]
please try the HEAD commit of my fork of this library:
https://github.com/psteinb/FourierConvolutionCUDALib.git
the error should be gone (tested on CentOS 7 with cuda 8.0.44)

**Comment by psteinb** [comment]
fixed in master, please check on your side and close this issue. thanks!

**Comment by aarpon** [comment]
I'll check asap! Thanks a lot!

**Comment by aarpon** [comment]
It works. Thanks!
