### ISSUE TITLE
Windows compiler error : enumeration value is out of "int" range while building test_how_cufft_works

### ISSUE THREAD

**Issue by RichardMyers** [StephanPreibisch/FourierConvolutionCUDALib#18]
I'm trying to build on a Windows 10 x64 system and get the following error using boost_1_58_0 for prebuild binaries [boost_1_58_0-msvc-12.0-64](https://sourceforge.net/projects/boost/files/boost-binaries/1.58.0/boost_1_58_0-msvc-12.0-64.exe/download).

"c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj" (default target) (8) ->
(CustomBuild target) ->
  I:/boost_1_58_0\boost/test/utils/basic_cstring/basic_cstring.hpp(60): error : enumeration value is out of "int" range [C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]

```
123 Warning(s)
1 Error(s)
```

**Comment by RichardMyers** [comment]
My exact build steps using CMake 3.3.1 on Windows 10 x64 are as follows:

1) download from github FourierConvolutionCUDALib into directory c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib

2) download and install boost_1_58_0-msvc-12.0-64.exe into directory I:\boost_1_58_0

3) open VS2013 x64 Native Tools Command Prompt (as Administrator).

4) build project using cmake

```
c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib>mkdir build

c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib>cd build

c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build>cmake.exe -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX=I:/ftmp -DBOOST_LIBRARYDIR=I:\boost_1_58_0\lib64-msvc-12.0 -DBOOST_ROOT=I:\boost_1_58_0 ..
-- The CXX compiler identification is MSVC 18.0.21005.1
-- The C compiler identification is MSVC 18.0.21005.1
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler using: Visual Studio 12 2013 Win64
-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
>> Setting up Release build
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.0 (found version "7.0")
>> compiling for Compute Capability 2.x, 3.0 and 3.5 only
>> [Windows] 64bit build detected, size of void pointer 8
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
>> static Boost UTF: optimized;I:/boost_1_58_0/lib64-msvc-12.0/libboost_system-vc120-mt-1_58.lib;debug;I:/boost_1_58_0/lib64-msvc-12.0/libboost_system-vc120-mt-gd-1_58.lib;optimized;I:/boost_1_58_0/lib64-msvc-12.0/libboost_filesystem-vc120-mt-1_58.lib;debug;I:/boost_1_58_0/lib64-msvc-12.0/libboost_filesystem-vc120-mt-gd-1_58.lib;optimized;I:/boost_1_58_0/lib64-msvc-12.0/libboost_unit_test_framework-vc120-mt-1_58.lib;debug;I:/boost_1_58_0/lib64-msvc-12.0/libboost_unit_test_framework-vc120-mt-gd-1_58.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/build
```

4) build artifacts using cmake

```
C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/build> cmake.exe --build . --target ALL_BUILD --config Release
"c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj" (default target) (8) ->
(CustomBuild target) ->
I:/boost_1_58_0\boost/test/utils/basic_cstring/basic_cstring.hpp(60): error : enumeration value is out of "int" range [C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]

123 Warning(s)
1 Error(s)
```

5) run tests

```
c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build>ctest.exe -C Release
Test project C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/build
    Start 1: gpu_convolve
1/1 Test #1: gpu_convolve .....................***Failed    0.50 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.53 sec

The following tests FAILED:
          1 - gpu_convolve (Failed)
Errors while running CTest
```

**Comment by RichardMyers** [comment]
I tried calling cmake with -DCUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5" and also v6.5 toolkit.

I get different compiler errors with v7.5 and same error with test_how_cufft_works when using the v6.5 toolkit.

**Comment by RichardMyers** [comment]
I also just tried first cmake with -DBOOST_ROOT=I:\boost_1_62_0 to use  boost_1_62_0-msvc-12.0-64, but still compile errors.

**Comment by RichardMyers** [comment]
I've tried using Visual Studio 10.0 and corresponding boost 1.58 but still not luck:

cmake.exe -G "Visual Studio 10 2010 Win64" -DCMAKE_INSTALL_PREFIX=I:/ftmp -DCUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5" -DBOOST_LIBRARYDIR=I:\boost_1_58_0\lib64-msvc-10.0 -DBOOST_ROOT=I:\boost_1_58_0 ..

"c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_gpu_convolve.vcxproj" (default target) (5) ->
(ClCompile target) ->
  c:\users\richard\documents\github\fourierconvolutioncudalib\tests\test_fixtures.hpp(68): error C2668: 'std::pow' : ambiguous call to overloaded function [C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tes
ts\test_gpu_convolve.vcxproj]
  c:\users\richard\documents\github\fourierconvolutioncudalib\tests\test_fixtures.hpp(97): error C2668: 'std::pow' : ambiguous call to overloaded function [C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tes
ts\test_gpu_convolve.vcxproj]
  c:\users\richard\documents\github\fourierconvolutioncudalib\tests\test_fixtures.hpp(121): fatal error C1903: unable to recover from previous error(s); stopping compilation [C:\Users\Richard\Documents\GitHub\FourierConvoluti
onCUDALib\build\tests\test_gpu_convolve.vcxproj]

"c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj" (default target) (8) ->
(CustomBuild target) ->
  C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(350): error : more than one instance of overloaded function "std::pow" matches the argument list: [C:\Users\Richard\Documents\GitHub\
FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]
  C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(352): error : more than one instance of overloaded function "std::pow" matches the argument list: [C:\Users\Richard\Documents\GitHub\
FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]
  C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(519): error : more than one instance of overloaded function "std::pow" matches the argument list: [C:\Users\Richard\Documents\GitHub\
FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]
  C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(551): error : more than one instance of overloaded function "std::pow" matches the argument list: [C:\Users\Richard\Documents\GitHub\
FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]
  C:/Users/Richard/Documents/GitHub/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(585): error : more than one instance of overloaded function "std::pow" matches the argument list: [C:\Users\Richard\Documents\GitHub\
FourierConvolutionCUDALib\build\tests\test_how_cufft_works.vcxproj]

**Comment by psteinb** [comment]
hi richard, thanks for reporting this. I am in the process of looking into this library again and porting it to cuda 8. for your particular problem, I have to admit that I don't have a win10 machine unfortunately. I can however offer to supply a cmake flag that will switch off testing. it's not the best, but it would a solution for you to go forward.

**Comment by psteinb** [comment]
please try the HEAD commit of my fork of this library:
https://github.com/psteinb/FourierConvolutionCUDALib.git
and call:

```
cmake -DENABLE_TESTING=OFF <other flags> ..
```

this way you can continue working

**Comment by RichardMyers** [comment]
Thanks @psteinb, I actually wanted to run the tests.  It does seem to build the dlls and three test programs: test_gpu_convolve,exe, test_gpu_memory_reach.exe and test_gpu_numerical_stability.exe .

I am rebuilding because I get a silent crash/quit running deconvolution using the SPIM_Registration plugin in Fiji.  The crash occurs on two systems, both x64 - one is this Win 10 system and the other is a 8.1 server system.   I think it's actually related to the compute level used for compiling.

I also tried to [patch](https://www.microsoft.com/en-us/download/details.aspx?id=48129) my Visual Studio 2013, but that did not fix the compile issues.

**Comment by RichardMyers** [comment]
Ok - I think we can close this case.  I sync'd to your branch and built with these steps:

```
c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib-psteinb\build>cmake.exe -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX=I:/ftmp -DCUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5" -DBOOST_LIBRARYDIR=I:\boost_1_58_0\lib64-msvc-12.0 -DBOOST_ROOT=I:\boost_1_58_0 ..

c:\Users\Richard\Documents\GitHub\FourierConvolutionCUDALib-psteinb\build>cmake.exe --build . --target ALL_BUILD --config Release
```

It builds the file FourierConvolutionCUDALib.dll without error.

If you need some independent testing of your CUDA 8.0 changes, just let me know and I'll be happy to give it a try.

I tested your branch on a bead image in Fiji with regions from 32x32x32 up to 256x256 worked but  384x384 and 512x512 failed with memory error:

```
Exception in thread "Thread-30" java.lang.Error: Invalid memory access
    at com.sun.jna.Native.invokeVoid(Native Method)
    at com.sun.jna.Function.invoke(Function.java:374)
    at com.sun.jna.Function.invoke(Function.java:323)
    at com.sun.jna.Library$Handler.invoke(Library.java:236)
    at com.sun.proxy.$Proxy11.convolution3DfftCUDAInPlace(Unknown Source)
    at spim.process.fusion.deconvolution.MVDeconFFTThreads.convolve1BlockCUDA(MVDeconFFTThreads.java:65)
    at spim.process.fusion.deconvolution.MVDeconFFT.convolve1(MVDeconFFT.java:420)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:362)
    at spim.process.fusion.deconvolution.MVDeconvolution.runIteration(MVDeconvolution.java:330)
    at spim.process.fusion.deconvolution.MVDeconvolution.<init>(MVDeconvolution.java:177)
    at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:259)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
    at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:88)
    at spim.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:57)
    at java.lang.Thread.run(Thread.java:745)
```

I'm testing on a Quadro K2200 (mem=4096, cuda capability = 5.0)

I think this memory issue is a known constraint.  If not, let me know and I can start a case for it.

**Comment by psteinb** [comment]
that is semi-good news, I'd say. the `512**3` image would consume .5GB in RAM. for power-of-2 transforms, cufft typically consumes around 2.5x the memory of the input signal. it's quite strange that it would go up to 8x and run against the memory wall of your device. 
are you using the K2200 for rendering the display as well? Another thing to try out would be to make the nvidia SDK examples `./3_Imaging/convolutionFFT2D` or `./7_CUDALibraries/simpleCUFFT` match `512**3` or `384**3` for single precision inputs. this way you could test your hypothesis stated above independent of fiji and friends.
