### ISSUE TITLE
`how_cufft_works` fails on P100/V100

### ISSUE THREAD

**Issue by psteinb** [StephanPreibisch/FourierConvolutionCUDALib#26]
with cuda 8.0.61 and a GTX Titan X, I see:

```
$ ctest
Test project /home/steinbac/development/FourierConvolutionCUDALib/build
    Start 1: gpu_convolve
1/3 Test #1: gpu_convolve .....................   Passed    4.00 sec
    Start 2: gpu_numerical_stability
2/3 Test #2: gpu_numerical_stability ..........   Passed    4.75 sec
    Start 3: how_cufft_works
3/3 Test #3: how_cufft_works ..................   Passed    4.07 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =  12.83 sec
```
#25 reports that this is not true with a P100.

**Comment by psteinb** [comment]
@mcahn Alright, it'll take me to next week to get access to a P100. I'll keep you posted.

**Comment by mcahn** [comment]
Thanks, Peter.

-- Matthew

**Comment by psteinb** [comment]
reproduced it:

```
$ ./tests/test_how_cufft_works 
Running 16 test cases...
/home/steinba/development/FourierConvolutionCUDALib/tests/test_how_cufft_works.cu(411): fatal error: in "inplace/cube_128_shape": l2norm = 0.000113907 not smaller than 0.0001

*** 1 failure is detected in the test module "TEST_HOW_CUFFT_WORKS"
```

the error occurs on the V100 as well, but doesn't on a K40c in the same system.

**Comment by psteinb** [comment]
I'd like to check a couple of other things first but potentially may file a bug report with nvidia, as the error points at a numerical inconsistency that shouldn't be there AFAIK. nvidia bug ID: 2015195

**Comment by mcahn** [comment]
My apologies, I reported this incorrectly in issue #26...
On the P100, how_cufft_works passes with cudatoolkit 8.0, but fails with cudatoolkit 9.0.  I said it backwards before.  But since you've duplicated it, it probably doesn't mater.

-- Matthew

**Comment by psteinb** [comment]
this was reported to nvidia and will be fixed in an upstream release. ;) bug id 2015195. I am closing this issue as the source is in the CUDA SDK.
