### ISSUE TITLE
Multiview-Deconvolution with CUDA is very slow compared to CPU

### ISSUE THREAD

**Issue by tibuch** [StephanPreibisch/FourierConvolutionCUDALib#6]
Hi @StephanPreibisch 

I applied a Multiview-Deconvolution to some registered images.

I computed the Multiview-Deconvolution once on CPU and once with CUDA. On CPU it took 10 min and with CUDA it took 45min. 

The cropped stack has a size of 546x700x728. 
Other configuration details:
Optimization I
OSEM acceleration: 1
10 Iterations
Use Tikhonov regularization: 0.0060

On CPU:
Compute entire image at once

With CUDA:
Blocksize: 256x256x256
Fused image: 1061MB, required total memory ~18037MB

PSF from beads.

I use a NVIDIA GTX 640 graphic card.

I also did some [measurements](http://i.imgur.com/qSler8u.png) and I don't understand the fwdX() call which takes so long. Looks like all the improvements with CUDA are lost because of this call.

Do you have any ideas how i can speed things up?

Thank you!

**Comment by psteinb** [comment]
Is that the eclipse profiler? how did you produce that screenshot!

moreover your screen shot suggests, that the cuda alg only takes 22% of 
the overall runtime. the rest is consumed by java. That ratio was better 
in the past.

btw, your comparison is a bit unfair as with the CPU you take the entire 
stack and with the GPU you require the image to be chunked in blocks.

I suggest:

a) share how you made these numbers, i.e. which plugin did you use?
b) try to use the same configuration for you measurements?
c) if you have the data somewhere that I can get a hold of, I could 
rerun it here.

Best,
P

**Comment by tibuch** [comment]
This is the Java VisualVM profiler and this is not a profile of the whole deconvolution. 

Okay I do a complete profile of the CPU and CUDA implementation with exact the same configuration.

I check if I can give you the data.

**Comment by tibuch** [comment]
I did some more testing with a better GPU (and same configuration) and now the GPU is definitely faster! 
Sorry about this issue.

**Comment by StephanPreibisch** [comment]
Hi, what is very important is to look at the "effective size of a block". If you for example use 256x256x256 blocks and your transformed PSF's are very big it can mean that per computed block you might just update a small fraction, e.g. 64x100x121 or so, which means a lot of block might have to be computed. This results from the fact that half of the PSF size needs to be computed, but cannot be used in the final result ...

**Comment by psteinb** [comment]
Just revisiting this thread, looks like this can be closed? if not, please reopen.
