### ISSUE TITLE
Having trouble following Windows build instructions

### ISSUE THREAD

**Issue by spimager** [StephanPreibisch/FourierConvolutionCUDALib#7]
I can't seem to find the NVCC Linker options you mentioned in your instructions.
I tried in VS 2013 and 2015 and none of these options seem to be there.

**Comment by psteinb** [comment]
Hi - thank you for your issue. But can you be more explicit about what you did? What CUDA Release are you using? Have you tried the CMAKE based build?
Best - P

**Comment by jpabbuehl** [comment]
Dear

thank you for developing this fiji package for SPIM processing.
Unfortunately, I am unfamiliar with Visual Studio 2015 community and how to build on Windows. I have 20Tb of data I would like to deconvolve and do segmentation but the processing is a huge bottleneck in my project
Could you please provide a more detailed tutorial ?
Here's what I did so far: install Cuda/Visual studio/Nsight
Fork your github on my account and clone this repository.

![howto](https://cloud.githubusercontent.com/assets/2730222/10163731/2d0845a0-66b5-11e5-9130-810b8f5e0eed.jpg)

After I create a shared project, that's where I am but I can't find build function in project
![howto2](https://cloud.githubusercontent.com/assets/2730222/10163882/180b1eb0-66b6-11e5-8d6e-7b2eb47c809c.jpg)

Unfortunately, I dont have access to a machine with Linux on it, so I have to stick with Windows.
Thank you in advance for your help.
Best
Jean-Paul

**Comment by psteinb** [comment]
Hi Jean-Paul - thank you for continuing this issue. I wasn't sure, if I could close it.

So, I believe you installed microsoft visual studio and cuda on your windows box. there is one more thing to install, which is cmake! I do not recommend building this package from within nsight (I should make it more clear in the Readme).

In any case install cmake, cuda and msvs, then open a command prompt. check if cmake is available by typing:

```
$ cmake.exe --help
```

![cmake_terminal](https://cloud.githubusercontent.com/assets/1465603/10166334/d1035b00-66c3-11e5-8e23-bc1ecc82681a.png)

the proper help message should pop up (see excerpt above). If that is done, go ahead and follow these instructions:

```
$ cd X:\path\to\repo
$ mkdir build
$ cd build
$ cmake.exe -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX=C:/msys64/home/steinbac/ftmp ..
$ cmake.exe --build . --target ALL_BUILD --config Release #ignore the warnings, report any errors on github
$ cmake.exe --build . --target install --config Release
```

I just did that with a clean clone of this repo and installed the library and it's headers into `C:/msys64/home/steinbac/ftmp` which is used as an example here.

**Comment by psteinb** [comment]
any news on this? Or can we close this issue?

**Comment by psteinb** [comment]
closing this now. I any problems on windows prevail, please reopen.
